AWSTemplateFormatVersion: "2010-09-09"

Resources: 
  EC2Role: 
    Type: "AWS::IAM::Role"
    Properties: 
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
        - "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
  EC2RolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "EC2RolePolicies"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: [
                "autoscaling:CompleteLifecycleAction",
                "ec2:DescribeInstances",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeAvailabilityZones",
                "ec2:RebootInstances",
                "ec2:StartInstances",
                "ec2:StopInstances"
                  ]
            Resource: [
              !Sub "arn:aws:autoscaling:ca-central-1:${AWS::AccountId}:autoScalingGroup:*:autoScalingGroupName/*",
              !Sub "arn:aws:ec2:ca-central-1:${AWS::AccountId}:instance/*" 
              ]
      Roles: 
        - 
          Ref: "EC2Role"
  EC2RoleInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      InstanceProfileName : "EC2RoleInstanceProfile"
      Path: "/"
      Roles: 
        - 
          Ref: "EC2Role"

